### ISSUE TITLE
Devices do not refresh (quick enough)

### ISSUE THREAD

**Issue by cyrano1966** [mario-peters/Domoticz-Home-Connect-Plugin#8]
When a change is done (e.g. selecting a new programme) after a few hours of running the weblistener, the new status is not refreshed via the api. I also noticed in the logs that reconnection takes 1 more minute in each cycle. May that be the reason?

**Comment by d-EScape** [comment]
Great to see these feature being added. Thanks!

I don’t see any update either. The values are immediately updated when I restart the plugin (update button on the configuration screen). Have not yet run a dishwasher cycle, but checked things like door open status.

**Comment by mario-peters** [comment]
> When a change is done (e.g. selecting a new programme) after a few hours of running the weblistener, the new status is not refreshed via the api. I also noticed in the logs that reconnection takes 1 more minute in each cycle. May that be the reason?

Could you please send me the homeconnectSSE_<device>.log and the domoticz.log from the timestamp on which you experienced this problemen.

**Comment by mario-peters** [comment]
> Great to see these feature being added. Thanks!
> 
> I don’t see any update either. The values are immediately updated when I restart the plugin (update button on the configuration screen). Have not yet run a dishwasher cycle, but checked things like door open status.

Could you please send me the homeconnectSSE_<device>.log and the domoticz.log from the timestamp on which you experienced this problemen.

**Comment by d-EScape** [comment]
Problem solved. The #!/usr/bin/python3 is missing from homeconnectSSE.py.

Since the init.d file also is not explicitly calling python the os will have no idea what to do with the file, and the daemon simply does not run at all. I am surprised this worked in your setup(?)

**Comment by mario-peters** [comment]
Did you update the homeconnectSSE.sh file?
I removed the #!/usr/bin/python3 from the homeconnectSSE.py file and changed the startup command in the homeconnectSSE.sh file so the OS knows what to do with the file.

**Comment by d-EScape** [comment]
Nope... I just did a git pull and was not aware of any manual steps needed. Maybe you can include info like that in the change log(?) Anyway, it's working now and updates immediately :)

**Comment by cyrano1966** [comment]
An update from my side.
- I am using the cloned git of last version (no python line in .py files)
- Daemon started/Hardware device started in domoticz
- Run without issues for 5 hours (e.g. change of washing programme in HC app was immediately shown in Domoticz Active Programme device)
- After 5 hours, daemon is still active/running but stopped logging the usual line (2020-11-03 22:31:43,081 message: [[]]
)
- Nothing unusual in logs
- Changes in HC App are not reflected anymore - If Domoticz HW Is restarted (Update), Active Programme shows "Failed", no updates from app - If Daemon restarted everything backs to normal

Note: My broadband was down for some minutes within the 5 hours (or about the 5 hours time). Can this be related to the issue?

**Comment by mario-peters** [comment]
- The homeconnectSSE.py doesn't need any python line anymore. Look at line 13 of the homeconnectSSE.sh file Did you change this in your device specific homeconnectSSE.sh
- Losing your internet connection does indeed effect this. The Domoticz plugin and the homeconnectSSE.py are both connecting to the Home Connect API on the internet. So losing the connection will disrupt both.

**Comment by mario-peters** [comment]
> Nope... I just did a git pull and was not aware of any manual steps needed. Maybe you can include info like that in the change log(?) Anyway, it's working now and updates immediately :)

Sorry, will think about it next time I change homeconnectSSE.sh. :-)

**Comment by cyrano1966** [comment]
@mario-peters : Regarding the lost connectivity. I understand the HC API will not be available while broadband is down, but should not the daemons reconnect when broadband is back without a manual restart?

**Comment by d-EScape** [comment]
I agree with @cyrano1966 that the plugin and daemon should be able to handle (temporary) connection issues.

In my setup the succes was also short lived. The plugin would immediately update the door opened/closed while testing, but it looks like it stopped updating values the same day. I'm running the dishwasher now and had to restart the daemon and the plugin to get the status updated. After that the door status, operation state, and active program where immediately updated. The remaining program time and estimated time took a bit longer to updated and the current program state does not seem to get any value (after about 5 minutes). 

There is nu indication of connection errors in any of the logs.

I don't see any errors in the domoticz log (have logging my level set to error, so no status messages either)

This is in the homeconnectSSE_Dishwasher.log:
atobm:  bad character '2' on line 1
atobm:  bad character '0' on line 1
atobm:  bad character '2' on line 1
atobm:  bad character '0' on line 1
atobm:  bad character '1' on line 1
atobm:  bad character '1' on line 1
atobm:  bad character '0' on line 1
atobm:  bad character '5' on line 1
atobm:  bad character ' ' on line 1
atobm:  bad character '0' on line 1
atobm:  bad character '7' on line 1
atobm:  bad character ':' on line 1
atobm:  bad character '5' on line 1
atobm:  bad character '0' on line 1
atobm:  bad character ':' on line 1
atobm:  bad character '2' on line 1
atobm:  bad character '9' on line 1
atobm:  bad character ',' on line 1
atobm:  bad character '2' on line 1
atobm:  bad character '9' on line 1
atobm:  bad character '8' on line 1
atobm:  bad character ' ' on line 1
atobm:  bad character 'S' on line 1
atobm:  bad character 't' on line 1
atobm:  bad character 'a' on line 1
atobm:  bad character 'r' on line 1
atobm:  bad character 't' on line 1
atobm:  bad character '.' on line 1
atobm:  bad character '.' on line 1
atobm:  bad character '.' on line 1
atobm:  line 2 is 55 characters wide instead of 32

**Comment by mario-peters** [comment]
> @mario-peters : Regarding the lost connectivity. I understand the HC API will not be available while broadband is down, but should not the daemons reconnect when broadband is back without a manual restart?

I agree on both off you and I will put this on my "ToDo"-list.
Will close this issue now.
